DROP TABLE IF EXISTS "reports" CASCADE;
DROP TABLE IF EXISTS "notifications" CASCADE;
DROP TABLE IF EXISTS "follows" CASCADE;
DROP TABLE IF EXISTS "likes" CASCADE;
DROP TABLE IF EXISTS "comments" CASCADE;
DROP TABLE IF EXISTS "image_tags" CASCADE;
DROP TABLE IF EXISTS "media_tags" CASCADE;
DROP TABLE IF EXISTS "tags" CASCADE;
DROP TABLE IF EXISTS "media_albums" CASCADE;
DROP TABLE IF EXISTS "image_albums" CASCADE;
DROP TABLE IF EXISTS "albums" CASCADE;
DROP TABLE IF EXISTS "media" CASCADE;
DROP TABLE IF EXISTS "images" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

DROP TYPE IF EXISTS "report_status";
DROP TYPE IF EXISTS "notification_type";
DROP TYPE IF EXISTS "media_type";

DROP FUNCTION IF EXISTS trigger_set_timestamp();
